name: random_quote_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  share_plus: ^11.0.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/